---
title: "BookStats"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("processData.R")

```

# Reading the World


```{r echo= FALSE}

pal.all <- colorFactor(palette = c("#8d96a3", "#fdbb84", "#e34a33"),
                        domain = world.dat.new@data$all.bin)
                   
labels.all <- sprintf(
  "<strong>%s</strong><br/>Books Owned - %g <br />Books Read - %g",
  world.dat.new@data$ADMIN, world.dat.new@data$own.count, world.dat.new@data$read.count
) %>% lapply(htmltools::HTML)

leaflet(data = world.dat.new) %>%
  addPolygons(fillColor = ~pal.all(all.bin),
              weight = 0.5,
              opacity = 1,
              color = "black",
              fillOpacity = 0.7,
              highlightOptions = highlightOptions(color = "white", weight = 2, bringToFront = TRUE),
              label = labels.all,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto")) %>%
  addLegend(pal = pal.all, values = ~all.bin, opacity = 0.7, title = "Read Status",
            position = "bottomright")



``` 